### ISSUE TITLE
이벤트 상세 포스터 하단 테두리와 이미지 사이 여백 처리 

### ISSUE THREAD

**Issue by jheeju** [o-cup/o-cup-web#116]
## 버그 내용 
이벤트 상세 포스터 하단 테두리와 이미지 사이에 여백이 발생함

## 재현 방법 
임의의 이벤트 상세 페이지로 이동하여 포스터 확인
<img width="1249" alt="스크린샷 2022-08-17 오후 11 20 45" src="https://user-images.githubusercontent.com/61128600/185158526-e8d86b98-1da7-4829-b838-082bde6b478f.png">

**Comment by hjnk125** [comment]
몰랐던 정보를 찾아서 공유합니당~~!
https://junistory.blogspot.com/2017/07/blog-post_25.html
