### ISSUE TITLE
신청 승인 처리용 admin 페이지 구현 

### ISSUE THREAD

**Issue by jheeju** [o-cup/o-cup-web#74]
## 이슈
신청 승인 처리용 admin 페이지 구현

## 태스크
- 신청 내역 확인 후 승인할 수 있는 화면 간단한 스타일만 적용하여 구현하기
- events 테이블에 `requested`, `approved` 컬럼 생성
- admin용 리포지토리 생성 또는 비공개 url로 설정 (논의 필요)

**Comment by hjnk125** [comment]
events 테이블에 `isRequested`, `isApproved`, `requestedBiases` 컬럼 생성하였습니당

**Comment by hjnk125** [comment]
승인 처리용 admin 페이지 
별도의 repo에 작업중! 이슈 닫습니당
